# build stage
FROM golang:1.25 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o todo-service cmd/ToDoList/main.go
RUN ls /app

# runtime stage
FROM alpine:3.14

WORKDIR /root
COPY --from=builder /app/todo-service .

EXPOSE 8080
CMD [ "./todo-service" ]